#!/bin/sh

if [ ! -d /app/mysql/mysql ]
then
	echo Creating initial database...
	mysql_install_db --user=root > /dev/null
	echo Done!
fi

if [ ! -d /run/mysqld ]
then
	mkdir -p /run/mysqld
fi

echo "FLUSH PRIVILEGES;" > send
echo "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY "$MYSQL_ROOT_PASSWORD" WITH GRANT OPTION;" >> send

/usr/bin/mysqld --user=root --bootstrap --verbose=0 < send
rm -f send

exec /usr/bin/mysqld --user=root --console
