apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps-app
spec:
  ports:
    - port: 21
      protocol: TCP
      name: ftps
    - port: 21000
      protocol: TCP
      name: ftps-data
  selector:
    app: ftps-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps-app
spec:
  selector:
    matchLabels:
      app: ftps-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      containers:
        - name: ftps
          image: llaurent/ftps
          env:
            - name: FTPS_USER
              value: user
            - name: FTPS_PASSWORD
              value: pass
          ports:
            - containerPort: 21
              hostPort: 21
            - containerPort: 21000
              hostPort: 21000
          imagePullPolicy: Never