#!/bin/sh

apk add openrc lighttpd \
php7 php7-openssl php7-cgi php7-xml php7-pdo php7-mcrypt php7-session php7-mysqli php7-zlib php7-json \
 --no-cache

tar -xf /var/www/localhost/htdocs/wordpress.tar.gz --strip-components=1 -C /var/www/localhost/htdocs
rm -f /var/www/localhost/htdocs/wordpress.tar.gz

mkdir -p /var/www/localhost/htdocs/tmp
chmod 777 -R /var/www/

mkdir -p /var/run/lighttpd
touch /var/run/lighttpd/php-fastcgi.socket
chown -R lighttpd:lighttpd /var/run/lighttpd

sed -i 's/\/run\/lighttpd.pid/\/run\/lighttpd\/php-fast-cgi.socket/g' /etc/lighttpd/lighttpd.conf
sed -i 's/#   include "mod_fastcgi.conf"/include "mod_fastcgi.conf"/g' /etc/lighttpd/lighttpd.conf
sed -i 's/\/usr\/bin\/php-cgi/\/usr\/bin\/php-cgi7/g' /etc/lighttpd/mod_fastcgi.conf

openrc
touch /run/openrc/softlevel

MYSQL="mysql -h mysql -u root --password=pass"
$MYSQL -e 'CREATE DATABASE wordpress;'
$MYSQL wordpress < /wordpress.sql

# run
/usr/sbin/nginx && /usr/local/sbin/php-fpm